language: php

php:
  - 7.2
  - 7.4

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - phpenv config-add travis.php.ini
  - composer install --no-interaction

script:
  - composer test
