language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - phpenv config-add travis.php.ini
  - composer install --no-interaction

script:
  - composer test
