language: php

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.3.*"

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - phpenv config-add travis.php.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --no-interaction

script:
  - composer test
