services:
    surfnet_gssp.saml.metadata_controller:
        class: Surfnet\GsspBundle\Controller\MetadataController
        arguments:
          - '@surfnet_saml.metadata_factory'

    surfnet_gssp.saml.sso_controller:
        class: Surfnet\GsspBundle\Controller\SSOController
        arguments:
          - '@surfnet_saml.http.redirect_binding'
          - '@surfnet_gssp.configuration_container'
          - '@surfnet_gssp.state_handler.service'
          - '@surfnet_gssp.saml.reponse_context'
          - '@surfnet_gssp.logger'

    surfnet_gssp.saml.sso_return_controller:
        class: Surfnet\GsspBundle\Controller\SSOReturnController
        arguments:
          - '@surfnet_gssp.configuration_container'
          - '@surfnet_gssp.state_handler.service'
          - '@surfnet_gssp.service.response'
          - '@surfnet_gssp.saml.reponse_context'
          - '@surfnet_gssp.logger'

    surfnet_gssp.value_store.service:
        class: Surfnet\GsspBundle\Service\ValueStore\SessionValueStore
        public: true
        arguments:
          - '@session'

    surfnet_gssp.state_handler.service:
        class: Surfnet\GsspBundle\Service\StateHandler
        arguments:
          - '@surfnet_gssp.value_store.service'

    surfnet_gssp.saml.signing_service:
        class: Surfnet\GsspBundle\Saml\AssertionSigningService
        arguments:
          - '@surfnet_saml.hosted.identity_provider'

    surfnet_gssp.saml.reponse_context:
        class: Surfnet\GsspBundle\Saml\ResponseContext
        arguments:
          - '@surfnet_saml.hosted.identity_provider'
          - '@surfnet_saml.remote.service_providers'
          - '@surfnet_gssp.state_handler.service'

    surfnet_gssp.service.datetime:
        class: Surfnet\GsspBundle\Service\DateTime\SystemDateTimeService

    surfnet_gssp.service.response:
        class: Surfnet\GsspBundle\Service\ResponseService
        arguments:
          - '@surfnet_saml.hosted.identity_provider'
          - '@surfnet_gssp.saml.reponse_context'
          - '@surfnet_gssp.saml.signing_service'
          - '@surfnet_gssp.service.datetime'

    Surfnet\GsspBundle\Service\AuthenticationService:
        class: Surfnet\GsspBundle\Service\StateBasedAuthenticationService
        arguments:
          - '@surfnet_gssp.state_handler.service'
          - '@router'
          - '@surfnet_gssp.logger'

    Surfnet\GsspBundle\Service\RegistrationService:
        class: Surfnet\GsspBundle\Service\StateBasedRegistrationService
        arguments:
          - '@surfnet_gssp.state_handler.service'
          - '@router'
          - '@surfnet_gssp.logger'

    surfnet_gssp.logger:
        class: Surfnet\GsspBundle\Logger\StepupRequestIdSariLogger
        arguments:
         - '@logger'
         - '@surfnet_saml.logger'
         - '@surfnet_gssp.state_handler.service'

    surfnet_gssp.monolog.request_id_processor:
        class: Surfnet\GsspBundle\Monolog\Processor\RequestIdProcessor
        tags:
            - { name: monolog.processor }

