# Install the "REMI" repo which contain newer php packages that override the default
# that come with the distro (CentOS7: 5.4; CentOS6: 5.3)
- name: Install REMI repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable REMI repo
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo

- name: Install common packages
  yum: name={{item}} state=present
  with_items:
  - vim
  - composer

- name: Install php-(cli)
  yum: name={{item}} state=present
  with_items:
  - php-cli
  - php-mbstring
  - php-mcrypt
  - php-intl
  - php-dom
  - php-xdebug

- name: Put php.ini
  template: src='php.ini.j2' dest='/etc/php.ini'

- name: Put default xdebug config
  template: src='files/xdebug.ini' dest='/etc/php.d/xdebug.ini'

# Composer install
- name: Run Composer installer.
  command: composer install
  args:
     chdir: "{{ app_root }}"
