#!/usr/bin/env bash

cd $(dirname $0)/../../

# https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage
./vendor/bin/phpcs --standard=ci/qa/phpcs.xml --report=full --warning-severity=0 --extensions=php ./src
./vendor/bin/phpcs --standard=ci/qa/phpcs_tests.xml --report=full --warning-severity=0 --extensions=php ./tests
