---

- name: Provision vagrant
  hosts: all
  become: true
  vars:
    app_root: "/vagrant"

  tasks:
  - name: Require Ansible 2
    assert:
      that: ansible_version.major == 2

  - include: tasks/main.yml

